# Generated by Django 5.0.7 on 2025-02-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='uploaded_at',
            new_name='uploaded_time',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(default='unknown.pdf', max_length=255),
        ),
    ]
